#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

USE_PM2=0
ASSUME_YES=0

for arg in "$@"; do
  case "$arg" in
    --pm2) USE_PM2=1 ;;
    -y|--yes) ASSUME_YES=1 ;;
    *)
      echo "Unknown option: $arg" >&2
      echo "Usage: scripts/setup.sh [--pm2] [--yes]" >&2
      exit 2
      ;;
  esac
done

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

random_secret() {
  openssl rand -base64 48 | tr -d '\n'
}

random_password() {
  openssl rand -base64 24 | tr -d '/+=' | head -c 24
}

prompt_value() {
  local label="$1"
  local fallback="$2"
  local value=""
  if [ "$ASSUME_YES" -eq 0 ] && [ -t 0 ]; then
    read -r -p "$label [$fallback]: " value
  fi
  printf '%s' "${value:-$fallback}"
}

prompt_secret() {
  local label="$1"
  local generated="$2"
  local value=""
  if [ "$ASSUME_YES" -eq 0 ] && [ -t 0 ]; then
    read -r -s -p "$label (leave blank to generate): " value
    echo
  fi
  printf '%s' "${value:-$generated}"
}

need_cmd node
need_cmd npm
need_cmd tmux
need_cmd openssl

NODE_MAJOR="$(node -p "Number(process.versions.node.split('.')[0])")"
if [ "$NODE_MAJOR" -lt 20 ]; then
  echo "Node.js 20+ is required. Found: $(node -v)" >&2
  exit 1
fi

if [ -f .env ]; then
  echo ".env already exists; leaving it untouched."
else
  ADMIN_USERNAME="$(prompt_value "Admin username" "admin")"
  ADMIN_PASSWORD="$(prompt_secret "Admin password" "$(random_password)")"
  JWT_SECRET="$(random_secret)"
  WEBHOOK_SECRET="$(random_secret)"
  ROOT_DIR="$(prompt_value "Terminal root" "$HOME")"
  HOST="$(prompt_value "Bind host" "127.0.0.1")"
  PORT_VALUE="$(prompt_value "Port" "3000")"

  umask 077
  cat > .env <<EOF
# Generated by scripts/setup.sh
PORT=$PORT_VALUE
TERMINUS_HOST="$HOST"
TERMINUS_ROOT="$ROOT_DIR"
TERMINUS_SHELL="${SHELL:-/bin/bash}"
TERMINUS_MAX_SESSIONS=20
TERMINUS_SCROLLBACK=10000
TERMINUS_READ_ONLY=false
TERMINUS_LOG_PATHS=/var/log,~/.pm2/logs

TERMINALX_AUTH_MODE=local
TERMINALX_ADMIN_USERNAME="$ADMIN_USERNAME"
TERMINALX_ADMIN_PASSWORD="$ADMIN_PASSWORD"
TERMINALX_JWT_SECRET="$JWT_SECRET"

# Optional Telegram bot. You can also configure this from Settings after login.
# TERMINALX_TELEGRAM_BOT_TOKEN=
# TERMINALX_TELEGRAM_WEBHOOK_URL=
# TERMINALX_TELEGRAM_WEBHOOK_SECRET=$WEBHOOK_SECRET
# TERMINALX_TELEGRAM_ALLOWED_USERS=123456789:$ADMIN_USERNAME
# TERMINALX_TELEGRAM_FORUM_CHAT_ID=-1001234567890
TERMINALX_TELEGRAM_MAX_TOPICS=10
EOF
  chmod 600 .env
  echo "Created .env with mode 0600."
  echo "Admin username: $ADMIN_USERNAME"
  echo "Admin password: $ADMIN_PASSWORD"
fi

npm ci
npm run build

if [ "$USE_PM2" -eq 1 ]; then
  if ! command -v pm2 >/dev/null 2>&1; then
    echo "pm2 is not installed. Install it with: npm install -g pm2" >&2
    exit 1
  fi
  pm2 start server/index.ts --name terminalx --interpreter ./node_modules/.bin/tsx --update-env
  pm2 save
  echo "TerminalX is running under pm2 as 'terminalx'."
else
  echo "Setup complete. Start with: npm run start"
fi
